### ISSUE TITLE
Cached manifest loop

### ISSUE THREAD

**Issue by Dxlls** [Mijago/D2ArmorPicker#81] opened 2022-10-25 16:35 UTC
When I log in through my bunige account it goes to update the cached manifest and after it does it logs me out. I've tried mobile and pc and nether is working for me.

**Comment by Mijago** [comment] 2022-10-25 16:39
Closing as its a duplicate of https://github.com/Mijago/D2ArmorPicker/issues/80

**Closed** 2022-10-25 16:41 UTC
