### ISSUE TITLE
Armour w/ Total Stats >42 In-Game Aren't Accounted For

### ISSUE THREAD

**Issue by Ryyyryyy** [Mijago/D2ArmorPicker#23] opened 2021-08-08 21:47 UTC
Pretty simple. Shaving off the extra 6.

![image](https://user-images.githubusercontent.com/53819669/128646544-c7de62bd-8093-40cd-81a1-03983fec5b5f.png)

With the mod active, the total MOB stat is 48. If it's applied, it does not show as a recommended loadout correctly:
![image](https://user-images.githubusercontent.com/53819669/128646643-75838c98-c673-4796-a919-3d2e2f28edc9.png)

However, if I take off the MOB mod, it is: 
![image](https://user-images.githubusercontent.com/53819669/128646600-a4797a86-39d7-4e16-a3c6-e27f3f06080f.png)

All armour without a stat line over 42 (but could be) function perfectly normally; only happens when all mods are active in-game.

**Comment by Mijago** [comment] 2021-08-09 12:11
Hi, this is a known issue ( #10 ). Sadly there is nothing I can do about this _at the moment_, as the general improvement of the page (especially memory issues) from #22 are more important to me at the moment.

The problem is that  the API cuts at 42 (and 0 for underflows) and I do not get the "real" values. I will research how DIM solved this issue in the future.

**Comment by SpencerCarstens** [comment] 2021-08-10 19:53
I think [this PR](https://github.com/DestinyItemManager/DIM/pull/5465) might be what you are looking for @Mijago.

This bug is quite a large snake in the grass. I thought I was going crazy when builds I had just found, masterworked, and added mods to were no longer showing up in the tool. 😓

**Comment by AOstarello** [comment] 2021-08-14 01:48
Oops, sorry, I just created a new issue that is exactly this.

**Comment by Mijago** [comment] 2021-08-14 06:48
> I think [this PR](https://github.com/DestinyItemManager/DIM/pull/5465) might be what you are looking for @Mijago.
> 
> This bug is quite a large snake in the grass. I thought I was going crazy when builds I had just found, masterworked, and added mods to were no longer showing up in the tool. 😓

Looks like this only displays a potentially incorrect base, but does not fix the parsing :(

**Comment by Mijago** [comment] 2021-08-14 06:49
Oh, I accidentally closed it. But that's not bad, let's continue this conversation in #29 as a combinatory issue für negative and positive capped items.

**Closed by Mijago** 2021-08-14 06:48 UTC
