### ISSUE TITLE
Results missing

### ISSUE THREAD

**Issue by Revadike** [Mijago/D2ArmorPicker#162] opened 2023-10-03 07:59 UTC
This seems like a bug.

Without strength filter:
![image](https://github.com/Mijago/D2ArmorPicker/assets/4411977/d6e569be-5b10-4ceb-bfea-7ef231b7ba3f)

With strength filter:
![image](https://github.com/Mijago/D2ArmorPicker/assets/4411977/72a55f44-6d13-4c69-a0f0-30dde7cebd27)

**Comment by Revadike** [comment] 2023-10-03 10:13
Sadly, these settings did nothing to fix the above issue:
![image](https://github.com/Mijago/D2ArmorPicker/assets/4411977/089646d6-b308-4e45-b979-8d29653d8d3b)

**Comment by jbccollins** [comment] 2023-10-03 22:44
This is just how the tool works. It's not a bug. If you want the stat tiers then pick them. Discussed extensively here: https://discord.com/channels/915562676808196126/915599133828612197/1107789819184169030

**Comment by Revadike** [comment] 2023-10-03 22:51
It's not showing all valid combinations with the selected settings, so it's a bug.

**Comment by jbccollins** [comment] 2023-10-04 00:03
Did you read through the discord link that I posted?

**Comment by TheMojoDojo** [comment] 2023-10-04 00:24
This is intended, D2AP won't make additional calculations beyond what is requested, unless in some cases where it can optimize wasted stats, which is not what was shown in these images. It's best to be as precise as possible when selecting stats so you get precise results.

**Comment by Revadike** [comment] 2023-10-04 06:46
I understand, but I respectfully disagree on how that should work. It does not make sense to me.

Here is my use case:
I select the 3 stats I would like maximized (t10), and I don't care about the rest of the stats. However, I want to maximize the stats total. Now, instead of simply sorting by total, I'll have to manually try different stat combinations, to see what results into the max total.

**Comment by jbccollins** [comment] 2023-10-04 14:33
Feel free to open a PR that changes this behavior then.

**Comment by Mijago** [comment] 2023-10-04 20:52
A piece of insight to the discussion: 

The reason why D2AP works like this is not a matter of "it should work like this", more of "it should run in an acceptable timespan".
Take the time it takes right now to compute the results, and now add (almost) the same time for every stat tier above your selection. We'd be at 10~30 seconds instead of 1.5~3 seconds per computation.

Because of this, there is still the manual part which allows the user to fine-tune results. Some guardians also prefer to see results with fewer mods - the current behavior allows you to see these and to maximize on demand.

I personally do not intend to change it anytime soon.

**Comment by Mijago** [comment] 2023-10-14 09:12
Closing for now. We can still discuss changes if anyone has good ideas, feel free to re-open it then.

**Closed** 2023-10-14 09:12 UTC
