### ISSUE TITLE
Tool still adding +2 stats to armour with "assume masterwork" disabled

### ISSUE THREAD

**Issue by AdamBarlow20** [Mijago/D2ArmorPicker#31] opened 2021-08-24 09:18 UTC
Even with "assume items are masterworked" disabled, the tool will filter out builds but still add +2 stats to armor pieces on the builds that it displays
![image](https://user-images.githubusercontent.com/80347974/130591113-45a4aad9-6f3f-418e-a41d-8c8e7c089315.png)
![image](https://user-images.githubusercontent.com/80347974/130591147-6becf1c7-5ada-4056-9f56-d986f90584a7.png)
![image](https://user-images.githubusercontent.com/80347974/130591212-8fae4304-5a6c-400e-9000-fc2ab5621417.png)

**Comment by hmmna** [comment] 2021-08-25 16:06
Wanted to try out this tool, but having exactly the same issue.

**Comment by Mijago** [comment] 2021-08-25 16:14
Does it just add it visually (only in the preview) or also on the full summary?
I'm not in town and can't test it right now.

Thanks for the report.

**Comment by AdamBarlow20** [comment] 2021-08-25 16:30
It does effect the full summary, it pretty much treats all the armor as masterworked within the entire sheet

**Comment by Trinity65** [comment] 2021-08-30 22:24
I’ve seen this same problem. The tool looks good and may be better than DIM loadout optimiser, but with adding 2 to every stat for Masterwork the results are skewed and so are not usable.

**Comment by Mijago** [comment] 2021-08-31 08:40
> I’ve seen this same problem. The tool looks good and may be better than DIM loadout optimiser, but with adding 2 to every stat for Masterwork the results are skewed and so are not usable.

To be honest, this ticked had a very low priority for me, as the issue is fixed in version 2. But as version 2 still needs some work, I'll fix it in v1 today, your point is definitely valid!
BTW, You can check out v2 by adding '/v2' to the URL ;)

**Comment by Mijago** [comment] 2021-08-31 10:19
So, i looked into it. Its a purely **visual** bug. the tool works as intended. It always assumes the class item to be masterworked.

**Comment by Mijago** [comment] 2021-08-31 10:23
![image](https://user-images.githubusercontent.com/3903469/131486234-70992440-ce57-49ac-97c0-a033b1207957.png)

As you can see, numbers check out. If you want, I can add another setting in V2 that allows to toggle the default masterwork for class items, but I won't edit it in v1.

**Closed by Mijago** 2021-08-31 10:23 UTC

**Comment by Trinity65** [comment] 2021-08-31 22:10
Thanks for the clarification on the class item. I can see what’s happening in the summary.
